### ISSUE TITLE
Slight modification of another repository. Copyright notice and permission notice should be included.

### ISSUE THREAD

**Issue by nejlag** [raghav64/SemiSuper_GAN#1]
The SemiSuper_GAN repository is the slight modification of https://github.com/nejlag/Semi-Supervised-Learning-GAN/blob/master/SSL_GAN.ipynb and hence the copyright notice and permission notice should be included:
 https://github.com/nejlag/Semi-Supervised-Learning-GAN/blob/master/LICENSE

**Comment by raghav64** [comment]
I am sorry, I am new to Git. Do you want me to copy your license or create my own?
